#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Add NVM path
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# Add /bin and /node_modules/.bin to path for every directory
path=(
  ./bin
  ./node_modules/.bin
  $path
)

# Add auto completion for /bin path
zstyle -e ':completion:*' command-path \
  '[[ -d $PWD/bin ]] && reply=($PWD/bin $path)'

# Add auto completion for node_modules/.bin path
zstyle -e ':completion:*' command-path \
  '[[ -d $PWD/node_modules/.bin ]] && reply=($PWD/node_modules/.bin $path)'

# Setup aliases
alias c='clear'

# Reload zshrc
alias reload='source ~/.zshrc'

# Add control + r history searching
bindkey '^R' history-incremental-search-backward

# Auto setup docker
eval $(docker-machine env default)

# zsh-autosuggestions - accept suggestion
bindkey '^e' autosuggest-accept

# Alt + arrow
bindkey '^[[1;3D' backward-word
bindkey '^[[1;3C' forward-word
