#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Setup aliases
alias ls='ls -GFlash'
alias c='clear'

# Reload zshrc
alias reload='source ~/.zshrc'

# Add Control + R history searching
bindkey '^R' history-incremental-search-backward

# Auto setup docker
eval $(docker-machine env default)
