#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Add NVM path
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# Setup aliases
alias c='clear'

# Reload zshrc
alias reload='source ~/.zshrc'

# Add Control + R history searching
bindkey '^R' history-incremental-search-backward

# Auto setup docker
eval $(docker-machine env default)

# zsh-autosuggestions - accept suggestion
bindkey '^e' autosuggest-accept

# alt + arrow
bindkey '^[[1;3D' backward-word
bindkey '^[[1;3C' forward-word
